name: Determine Release Type and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: NPM install
        run: npm install

      - name: Run JS script to set environment variable
        run: node scripts/set-env-vars.mjs

      - name: Use the environment variable
        run: echo "The value of RELEASE_TYPE => ${{env.RELEASE_TYPE}}"